### ISSUE TITLE
windows 10 install failed

### ISSUE THREAD

**Issue by darrenzo** [nornagon/electron-minidump#10]
$ npm install -g electron-minidump

> minidump@0.19.0 preinstall C:\Program Files\nodejs\node_modules\electron-minidump\node_modules\minidump
> node build.js

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path C:\Program Files\nodejs\node_modules\electron-minidump\node_modules\minidump\build\src\processor\minidump_stackwalk
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Program Files\nodejs\node_modules\electron-minidump\node_modules\minidump\build\src\processor\minidump_stackwalk'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ZWW\AppData\Roaming\npm-cache\_logs\2021-08-12T02_04_00_520Z-debug.log

**Comment by JaydenJane** [comment]
I have got the same error!!!

**Comment by nornagon** [comment]
I think this is fixed now!

**Comment by Kenny1zhao** [comment]
The problem still exists
