### ISSUE TITLE
Fails to install on MacOS 

### ISSUE THREAD

**Issue by Patronics** [nornagon/electron-minidump#6]
I get this error log when attempting to install on macOS (with either a global or local install), apparently it attempts to run chmod on a nonexistent file, which fails.

`npm ERR! code 254
npm ERR! git dep preparation failed
npm ERR! command /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --cache=/Users/patrickleiser/.npm/_cacache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm ERR! code ENOENT
npm ERR! npm ERR! syscall chmod
npm ERR! npm ERR! path /usr/local/lib/node_modules/minidump/build/src/processor/minidump_stackwalk
npm ERR! npm ERR! errno -2
npm ERR! npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/minidump/build/src/processor/minidump_stackwalk'
npm ERR! npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! npm ERR! enoent `

**Comment by rzhao271** [comment]
Same issue with 
WSL on Windows 10.

![wsl-example](https://user-images.githubusercontent.com/7199958/104662386-8e1c8080-567f-11eb-9829-d8c3d9a29a97.PNG)

**Comment by nornagon** [comment]
I think this is fixed now!
