### ISSUE TITLE
install fail on windows

### ISSUE THREAD

**Issue by weiweian90** [nornagon/electron-minidump#7]
clone of 'https://chromium.googlesource.com/breakpad/breakpad' failed

**Comment by bytemain** [comment]
it seems that you are working in China, maybe the `googlesource.com` are blocked by the Great Fire Wall.

**Comment by nornagon** [comment]
If above is the case then this is beyond my control to fix, unfortunately :/

**Comment by bytemain** [comment]
you can use a proxy, then set `git` to use it.

---

可以参考：https://gist.github.com/laispace/666dd7b27e9116faece6
